services:
  medux.api:
    image: ${DOCKER_REGISTRY-}meduxapi
    build:
      context: .
      dockerfile: Medux.Api/Dockerfile
  
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha
      - MONGO_INITDB_DATABASE=academia
    env_file:
      - ./Medux.Api/db.env
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
